before_script:
    - angr-test sync hard

local:
    script: "angr-test cle"
    tags:
        - "angr"

angr:
    script: "angr-test angr"
    tags:
        - "angr"

fidget:
    script: "angr-test fidget"
    tags:
        - "angr"

angrop:
    script: "angr-test angrop"
    tags:
        - "angr"

cle_lint:
    script: "angr-test lint"
    tags:
        - "angr"

docs:
    script: "angr-test docs"
    tags:
        - "angr"

