before_script:
    - angr-test sync hard

local:
    script: "angr-test cle"
    tags:
        - "angr"
    except:
        - "master"

angr:
    script: "angr-test angr"
    tags:
        - "angr"
    except:
        - "master"

fidget:
    script: "angr-test fidget"
    tags:
        - "angr"
    except:
        - "master"

cle_lint:
    script: "angr-test lint"
    tags:
        - "angr"
    except:
        - "master"
